config/routes.rb
Rails.application.routes.draw do

  mount Attachinary::Engine => "/attachinary"
  
  resources :images do
    resources :editions, shallow: true
  end
  resources :users

  root 'application#enter'

  get    'signup'  => 'users#new'
  get '/session' => 'session#current_user', defaults: { format: :json}
  post   'session'   => 'session#create'
  delete 'session'  => 'session#destroy'

end

app/models/edition.rb
class Edition < ActiveRecord::Base
  belongs_to :image
  has_one :user, through: :image
end

app/controllers/editions_controller.rb
class EditionsController < ApplicationController
  before_action :set_edition, only: [:show, :edit, :update, :destroy]

  # GET /editions
  # GET /editions.json
  def index
    image = Image.find(params[:image_id])
    @editions = image.editions
  end

  # GET /editions/1
  # GET /editions/1.json
  def show
    image = Image.find(params[:image_id])
    @edition = image.editions.find(params[:image_id])


  end

  # GET /editions/new
  def new
    image = Image.find(params[:image_id])
    @edition = image.editions
  end

  # GET /editions/1/edit
  def edit
  end

  # POST /editions
  # POST /editions.json
  def create
    image = Image.find(params[:image_id])
    @edition = image.editions.new(editions_params)
    @edition.image_id = @image.id

    respond_to do |format|
      if @edition.save
        format.html { redirect_to @edition, notice: 'Edition was successfully created.' }
        format.json { render :show, status: :created, location: @edition }
      else
        format.html { render :new }
        format.json { render json: @edition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /editions/1
  # PATCH/PUT /editions/1.json
  def update
    image = Image.find(params[:image_id])
    @edition = image.edition.find(params[:id])
    respond_to do |format|
      if @edition.update(edition_params)
        format.html { redirect_to @edition, notice: 'Edition was successfully updated.' }
        format.json { render :show, status: :ok, location: @edition }
      else
        format.html { render :edit }
        format.json { render json: @edition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /editions/1
  # DELETE /editions/1.json
  def destroy
    image = Image.find(params[:image_id])
    @edition = image.edition.find(params[:id])

    @edition.destroy
    respond_to do |format|
      format.html { redirect_to editions_url, notice: 'Edition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_edition
      @edition = Edition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def edition_params
      params.require(:edition).permit(:image_id, :id, :size, :number, :soldTo, :saleDate, :saleAmount, :numberRemaining)
    end
end

app/helpers/editions_helper.rb
module EditionsHelper
end

app/views/editions/_form.html.erb
<%= form_for(@edition) do |f| %>
  <% if @edition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@edition.errors.count, "error") %> prohibited this edition from being saved:</h2>

      <ul>
      <% @edition.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image_id %><br>
    <%= f.text_field :image_id %>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :soldTo %><br>
    <%= f.text_field :soldTo %>
  </div>
  <div class="field">
    <%= f.label :saleDate %><br>
    <%= f.date_select :saleDate %>
  </div>
  <div class="field">
    <%= f.label :saleAmount %><br>
    <%= f.text_field :saleAmount %>
  </div>
  <div class="field">
    <%= f.label :numberRemaining %><br>
    <%= f.number_field :numberRemaining %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/editions/edit.html.erb
<h1>Editing Edition</h1>

<%= render 'form' %>

<%= link_to 'Show', @edition %> |
<%= link_to 'Back', editions_path %>

app/views/editions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Editions</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Size</th>
      <th>Number</th>
      <th>Soldto</th>
      <th>Saledate</th>
      <th>Saleamount</th>
      <th>Numberremaining</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @editions.each do |edition| %>
      <tr>
        <td><%= edition.image %></td>
        <td><%= edition.size %></td>
        <td><%= edition.number %></td>
        <td><%= edition.soldTo %></td>
        <td><%= edition.saleDate %></td>
        <td><%= edition.saleAmount %></td>
        <td><%= edition.numberRemaining %></td>
        <td><%= link_to 'Show', edition %></td>
        <td><%= link_to 'Edit', edit_edition_path(edition) %></td>
        <td><%= link_to 'Destroy', edition, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Edition', new_edition_path %>

app/views/editions/new.html.erb
<h1>New Edition</h1>

<%= render 'form' %>

<%= link_to 'Back', editions_path %>

app/views/editions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= @edition.image %>
</p>

<p>
  <strong>Size:</strong>
  <%= @edition.size %>
</p>

<p>
  <strong>Number:</strong>
  <%= @edition.number %>
</p>

<p>
  <strong>Soldto:</strong>
  <%= @edition.soldTo %>
</p>

<p>
  <strong>Saledate:</strong>
  <%= @edition.saleDate %>
</p>

<p>
  <strong>Saleamount:</strong>
  <%= @edition.saleAmount %>
</p>

<p>
  <strong>Numberremaining:</strong>
  <%= @edition.numberRemaining %>
</p>

<%= link_to 'Edit', edit_edition_path(@edition) %> |
<%= link_to 'Back', editions_path %>