config/routes.rb
Rails.application.routes.draw do

  mount Attachinary::Engine => "/attachinary"
  
  resources :images do
    resources :editions, shallow: true
  end
  resources :users

  root 'application#enter'

  get    'signup'  => 'users#new'
  get '/session' => 'session#current_user', defaults: { format: :json}
  post   'session'   => 'session#create'
  delete 'session'  => 'session#destroy'

end

app/models/image.rb
class Image < ActiveRecord::Base
  has_attachments :photos
  belongs_to :users
  has_many :editions, dependent: :destroy
  accepts_nested_attributes_for :editions,
    :allow_destroy => true, :update_only => true
  # mount_uploader :picture, PictureUploader



  # validates_associated
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :require_current_user
  before_action :set_image, only: [:show, :edit, :update, :destroy]



  # GET /images
  # GET /images.json
  def index
    @images = @current_user.images
    current_user.images.includes(:editions)
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
    @image.editions.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = current_user.images.new(image_params)
    @image.user_id = current_user.id
    # @image.editions.first.current_user.id = current_user.id

    respond_to do |format|
      if @image.save
        format.html { redirect_to new_image_edition_path(@image), notice: 'Image was successfully created.' }
        format.json {
          render :show,
          status: :created,
          location: @image
        }
        # redirect_to new_image_edition_path(@image)
      else
        format.html { render :new }
        format.json {
          render json: @image.errors,
          status: :unprocessable_entity
        }
      end

    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        # format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:id, :filename, :title, :dateCreated, :users_id, {photos: []}, editions_attributes: [:size, :number, :soldTo, :saleDate, :saleAmount, :numberRemaining, :_destroy, :patch])
    end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<br>

<div class="container">
  <%= form_for(@image, :html => {class: 'col s12', :multipart => true}) do |f| %>
  <% if @image.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

    <ul>
      <% @image.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="row">
    <div class="input-field col s6">
      <%= f.label :'File Name' %><br>
      <%= f.text_field :filename, :placeholder => 'reference filename' %>
    </div>

  </div>
  <div class="row">
    <div class="input-field col s6">
    <%= f.label :'Title' %><br>
    <%= f.text_field :title %>
  </div>
  </div>
  <div class="row">
    <%= f.label :'Upload Image' %>
     <!-- <%= cl_image_upload_tag(:image_id) %> -->
    <%= f.attachinary_file_field :photos%>
  </div>
  <div class='row'>
    <div class="input-field col s6">
    <%= f.label :'Date Created' %><br>
    <%= f.date_field :dateCreated %>
  </div>
  </div>
</div>
<div class="container">
  <%= f.fields_for :editions do |e| %>
  <div class="row">
    <div class="input-field col s6">
    <%= e.label :'Image Size' %><br>
    <%= e.text_field :size %>
  </div>
  </div>
  <div class="row">
    <div class="input-field col s6">
    <%= e.label :'Number in Edition' %><br>
    <%= e.number_field :number %>
  </div>
  </div>
  <div class="row">
    <div class="input-field col s6">
    <%= e.label :'Sold To' %><br>
    <%= e.text_field :soldTo %>
  </div>
  </div>
  <div class="row">
    <div class="input-field col s6">
    <%= e.label :'Sale Date' %><br>
    <%= e.date_field :saleDate %>
  </div>
  </div>
  <div class="row">
    <div class="input-field col s6">
    <%= e.label :'Sale Amount' %><br>
    <%= e.text_field :saleAmount %>
  </div>
  </div>
  <div class="row">
    <div class="input-field col s6">
    <%= e.label :'Number Remaining' %><br>
    <%= e.number_field :numberRemaining %>
  </div>
  </div>
  <% end %>
</div>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form' %>

<%= link_to 'Show Image', @image %> |
<%= link_to 'All Images', images_path %>

app/views/images/index.html.erb
<div class="card" style="width:95%;margin:0 auto;margin-top:40px;padding:20px">

<p id="notice"><%= notice %></p>

<h1>Listing Images</h1>

<table class="highlight">
  <thead>
    <tr>
      <th>Filename</th>
      <th>Title</th>
      <th>Date created</th>
      <th>Image Preview</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image.filename %></td>
        <td><%= image.title %></td>
        <td><%= image.dateCreated %></td>
        <td>    <% image.photos.each do |photo| %>
                <%= cl_image_tag(photo.path, { size: '100x100', crop: :fit }) %>
            <% end %>
          </td>
        <td><%= link_to 'Show', image %></td>
        <td><%= link_to 'Edit', edit_image_path(image) %></td>
        <td><%= link_to 'Delete', image, method: :delete, data: { confirm: 'Are you sure? This action cannot be undone' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<hr>
<br>

</div>

app/views/images/new.html.erb
<div class="container">
  <h4 style="text-align:center;">New Image Details</h4>

  <%= render 'form' %>

  <%= link_to 'All Images', images_path %>

</div>

app/views/images/show.html.erb
<div class="card" style="width:95%;margin:0 auto;margin-top:40px;padding:20px; text-align:center;">
<p id="notice"><%= notice %></p>

  <h3 style="text-align:center;">Image Information</h3>
  <p>
    <strong>Filename:</strong>
    <%= @image.filename %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= @image.title %>
  </p>

  <p>
    <% @image.photos.each do |photo| %>
        <%= cl_image_tag(photo.path, { width: '500', crop: :fit }) %>
    <% end %>
  </p>



  <p>
    <strong>Datecreated:</strong>
    <%= @image.dateCreated %>
  </p>

  <p>
    <strong>User:</strong>
    <%= @image.user_id %>
  </p>

  <h3>Edition Information</h3>
  <% if @image.editions.any? %>
  <ul>
    <% @image.editions.each do |e| %>
    <li>Image Size: <%= e.size %></li>
    <li>Number in Edition: <%= e.number %></li>
    <li>Sold To: <%= e.soldTo %></li>
    <li>Sale Date: <%= e.saleDate %></li>
    <li>Sale Amount: <%= e.saleAmount %></li>
    <li>Number Remaining in Edition: <%= e.numberRemaining %></li>
  </ul>
  <%end%>
  <%end%>
  <%= link_to 'Edit', edit_image_path(@image) %> |
  <%= link_to 'All Images', images_path %>
</div>