config/routes.rb
Rails.application.routes.draw do

  mount Attachinary::Engine => "/attachinary"
  
  resources :images do
    resources :editions, shallow: true
  end
  resources :users

  root 'application#enter'

  get    'signup'  => 'users#new'
  get '/session' => 'session#current_user', defaults: { format: :json}
  post   'session'   => 'session#create'
  delete 'session'  => 'session#destroy'

end

app/views/layouts/_nav.html.erb
<nav class="navbar-fixed white z-depth-0">
  <ul class="right">
    <li> <a href="<%= images_path %>">Images</a></li>
    <li><a href="<%= new_image_path%>">New Image</a></li>
    <li><a href="#">User Profile</a></li>
    <% if current_user %>
    <hr/>
    <!-- <form action="<%= session_path %>" method="POST">
      <input type="hidden" name="authenticity_token"
        value="<%= form_authenticity_token %>">
      <input type="hidden" name="_method" value="DELETE">
      <input type="submit" value="Log Out!">
    </form>
    <% end %> -->

  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ArtVentory</title>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'app', 'data-turbolinks-track' => true %>
  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/css/materialize.min.css">
  <link href='https://fonts.googleapis.com/css?family=Roboto+Condensed:400,300' rel='stylesheet' type='text/css'>
  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/js/materialize.min.js"></script>
  <%= stylesheet_link_tag  'app', media: 'all', 'data-turbolinks-track' => true %>
  <%= cloudinary_js_config %>
  <%= csrf_meta_tags %>
</head>

<body>

  <%= render 'layouts/nav' unless @disable_nav %>

  <%= yield %>

</body>
</html>